terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 1: 29289 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 2: 29291 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 3: 29293 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 4: 29295 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 5: 29297 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 6: 29299 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 7: 29301 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 8: 29303 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 9: 29305 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 10: 29307 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 11: 29309 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 12: 29311 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 13: 29313 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 14: 29315 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 15: 29317 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 16: 29319 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 17: 29321 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 18: 29323 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 19: 29325 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 20: 29327 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 21: 29329 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 22: 29331 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 23: 29333 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 24: 29335 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 25: 29337 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 26: 29339 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 27: 29341 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 28: 29343 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 29: 29345 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 30: 29347 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 31: 29349 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 32: 29351 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 33: 29353 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 34: 29355 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 35: 29357 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 36: 29359 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 37: 29361 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 38: 29363 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 39: 29365 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 40: 29367 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 41: 29369 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/10.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-c-val.sh: line 42: 29371 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-a.pddl $1
