terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 1: 28728 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 2: 28730 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 3: 28732 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 4: 28734 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 5: 28736 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 6: 28738 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 7: 28740 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 8: 28742 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 9: 28744 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 10: 28746 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 11: 28748 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 12: 28750 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 13: 28752 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 14: 28754 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 15: 28756 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 16: 28758 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 17: 28760 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 18: 28762 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 19: 28764 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 20: 28766 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 21: 28768 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 22: 28770 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 23: 28772 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 24: 28774 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 25: 28776 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 26: 28778 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 27: 28780 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 28: 28782 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 29: 28784 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 30: 28786 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 31: 28788 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 32: 28790 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 33: 28792 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 34: 28794 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 35: 28796 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 36: 28798 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 37: 28800 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 38: 28802 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 39: 28804 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 40: 28806 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 41: 28808 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 42: 28810 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/2.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-0-d-val.sh: line 43: 28812 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-b.pddl $1
