terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 1: 31373 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 2: 31375 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 3: 31377 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 4: 31379 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 5: 31381 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 6: 31383 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 7: 31385 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 8: 31387 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 9: 31389 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 10: 31391 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 11: 31393 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 12: 31395 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 13: 31397 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 14: 31399 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 15: 31401 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 16: 31403 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 17: 31405 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 18: 31407 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 19: 31409 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 20: 31411 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 21: 31413 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 22: 31415 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 23: 31417 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 24: 31419 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 25: 31421 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 26: 31423 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 27: 31425 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 28: 31427 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 29: 31429 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 30: 31431 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 31: 31433 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 32: 31435 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 33: 31437 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 34: 31439 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 35: 31441 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 36: 31443 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 37: 31445 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 38: 31447 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 39: 31449 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/22.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-2-d-val.sh: line 40: 31451 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-b.pddl $1
