terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 1: 31877 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 2: 31879 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 3: 31881 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 4: 31883 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 5: 31885 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 6: 31887 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 7: 31889 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 8: 31891 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 9: 31893 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 10: 31895 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 11: 31897 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 12: 31899 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 13: 31901 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 14: 31903 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 15: 31905 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 16: 31907 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 17: 31909 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 18: 31911 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 19: 31913 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 20: 31915 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 21: 31917 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 22: 31919 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 23: 31921 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 24: 31923 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 25: 31925 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 26: 31927 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 27: 31929 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 28: 31931 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 29: 31933 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 30: 31935 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 31: 31937 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 32: 31939 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 33: 31941 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 34: 31943 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 35: 31945 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 36: 31947 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 37: 31949 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 38: 31951 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 39: 31953 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 40: 31955 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/30.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-b-val.sh: line 41: 31957 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-a.pddl $1
