terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 1: 32084 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 2: 32086 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 3: 32088 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 4: 32090 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 5: 32092 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 6: 32094 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 7: 32096 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 8: 32098 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 9: 32100 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 10: 32102 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 11: 32104 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 12: 32106 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 13: 32108 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 14: 32110 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 15: 32112 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 16: 32114 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 17: 32116 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 18: 32118 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 19: 32120 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 20: 32122 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 21: 32124 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 22: 32126 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 23: 32128 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 24: 32130 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 25: 32132 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 26: 32134 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 27: 32136 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 28: 32138 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 29: 32140 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 30: 32142 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 31: 32144 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 32: 32146 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 33: 32148 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 34: 32150 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 35: 32152 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 36: 32154 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 37: 32156 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 38: 32158 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 39: 32160 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 40: 32162 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/33.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-2-d-val.sh: line 41: 32164 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-d.pddl $1
