terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 1: 32167 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 2: 32169 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 3: 32171 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 4: 32173 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 5: 32175 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 6: 32177 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 7: 32179 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 8: 32181 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 9: 32183 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 10: 32185 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 11: 32187 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 12: 32189 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 13: 32191 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 14: 32193 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 15: 32195 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 16: 32197 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 17: 32199 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 18: 32201 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 19: 32203 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 20: 32205 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 21: 32207 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 22: 32209 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 23: 32211 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 24: 32213 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 25: 32215 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 26: 32217 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 27: 32219 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 28: 32221 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 29: 32223 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 30: 32225 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 31: 32227 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 32: 32229 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 33: 32232 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 34: 32234 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 35: 32236 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 36: 32238 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 37: 32240 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 38: 32242 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 39: 32244 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/34.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-4-1-b-val.sh: line 40: 32246 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-a.pddl $1
