terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 1: 32590 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 2: 32592 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 3: 32594 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 4: 32596 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 5: 32598 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 6: 32600 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 7: 32602 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 8: 32604 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 9: 32606 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 10: 32608 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 11: 32610 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 12: 32612 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 13: 32614 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 14: 32616 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 15: 32618 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 16: 32620 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 17: 32622 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 18: 32624 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 19: 32626 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 20: 32628 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 21: 32630 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 22: 32632 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 23: 32634 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 24: 32636 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 25: 32638 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 26: 32640 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 27: 32642 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 28: 32644 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 29: 32646 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 30: 32648 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 31: 32650 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 32: 32652 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 33: 32654 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 34: 32656 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 35: 32658 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 36: 32660 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 37: 32662 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 38: 32664 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 39: 32668 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/39.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-c-val.sh: line 40: 32670 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-d.pddl $1
