terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 1: 32673 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 2: 32675 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 3: 32677 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 4: 32679 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 5: 32681 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 6: 32683 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 7: 32685 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 8: 32687 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 9: 32689 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 10: 32691 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 11: 32693 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 12: 32695 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 13: 32697 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 14: 32699 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 15: 32701 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 16: 32703 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 17: 32705 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 18: 32707 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 19: 32709 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 20: 32711 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 21: 32713 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 22: 32715 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 23: 32717 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 24: 32719 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 25: 32721 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 26: 32723 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 27: 32725 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 28: 32727 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 29: 32729 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 30: 32731 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 31: 32733 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 32: 32735 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 33: 32737 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 34: 32739 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 35: 32741 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 36: 32743 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 37: 32745 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 38: 32747 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 39: 32749 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/40.neglite.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-2-3-d-val.sh: line 40: 32751 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-d.pddl $1
