terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 1: 28943 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 2: 28945 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 3: 28947 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 4: 28949 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 5: 28951 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 6: 28953 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 7: 28955 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 8: 28957 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 9: 28959 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 10: 28961 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 11: 28963 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 12: 28965 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 13: 28967 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 14: 28969 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 15: 28971 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 16: 28973 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 17: 28975 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 18: 28977 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 19: 28979 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 20: 28981 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 21: 28983 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 22: 28985 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 23: 28987 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 24: 28989 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 25: 28991 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 26: 28993 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 27: 28995 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 28: 28997 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 29: 28999 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 30: 29001 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 31: 29003 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 32: 29005 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 33: 29007 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 34: 29009 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 35: 29011 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 36: 29013 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 37: 29015 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 38: 29017 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 39: 29019 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 40: 29021 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 41: 29023 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/5.pos.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEGLITE-3-0-a-val.sh: line 42: 29025 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-a.pddl $1
