terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 1:   729 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 2:   731 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 3:   735 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 4:   737 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 5:   739 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 6:   741 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 7:   743 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 8:   746 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 9:   748 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 10:   751 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 11:   753 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 12:   756 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 13:   759 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 14:   761 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 15:   763 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 16:   765 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 17:   767 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 18:   769 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 19:   771 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 20:   773 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 21:   775 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 22:   777 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 23:   779 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 24:   781 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 25:   783 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 26:   785 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 27:   787 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 28:   789 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 29:   791 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 30:   793 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 31:   795 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 32:   797 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 33:   799 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 34:   801 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 35:   803 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 36:   805 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 37:   807 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 38:   812 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 39:   816 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 40:   818 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 41:   820 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/fibo/6.neg.program'
./scripts/neg/ijcai19/fibo-val/fibo-NEG-1-2-b-val.sh: line 42:   822 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/fibo/domain.pddl domains/neg/fibo/fibo-3-neg-a.pddl $1
