terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 1:  5325 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 2:  5327 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 3:  5329 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 4:  5331 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 5:  5333 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 6:  5335 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 7:  5337 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 8:  5339 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 9:  5341 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 10:  5343 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 11:  5345 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 12:  5347 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 13:  5349 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 14:  5351 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 15:  5353 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 16:  5355 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 17:  5357 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 18:  5359 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 19:  5361 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 20:  5363 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 21:  5365 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 22:  5367 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 23:  5369 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 24:  5371 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 25:  5373 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 26:  5375 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 27:  5377 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 28:  5379 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 29:  5383 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 30:  5385 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 31:  5387 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 32:  5389 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 33:  5391 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 34:  5393 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 35:  5395 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 36:  5397 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 37:  5399 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 38:  5401 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 39:  5403 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 40:  5405 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 41:  5407 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 42:  5409 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 43:  5411 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 44:  5413 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 45:  5415 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 46:  5417 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 47:  5419 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 48:  5421 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 49:  5423 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 50:  5425 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 51:  5427 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 52:  5429 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 53:  5431 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 54:  5433 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 55:  5435 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 56:  5437 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 57:  5439 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 58:  5441 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 59:  5443 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 60:  5445 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 61:  5447 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 62:  5449 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 63:  5451 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 64:  5453 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 65:  5455 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 66:  5457 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 67:  5459 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 68:  5461 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 69:  5463 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 70:  5465 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 71:  5467 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 72:  5469 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 73:  5471 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 74:  5473 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 75:  5475 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 76:  5477 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 77:  5479 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 78:  5481 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 79:  5483 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 80:  5485 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 81:  5487 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 82:  5489 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 83:  5491 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 84:  5493 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 85:  5495 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 86:  5497 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 87:  5499 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 88:  5503 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 89:  5505 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 90:  5510 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 91:  5513 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 92:  5519 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 93:  5521 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 94:  5526 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 95:  5528 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 96:  5530 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 97:  5532 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 98:  5534 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 99:  5536 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 100:  5538 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/10.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-3-1-b-val.sh: line 101:  5540 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-b.pddl $1
