terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 1: 31482 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 2: 31484 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 3: 31486 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 4: 31488 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 5: 31490 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 6: 31492 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 7: 31494 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 8: 31496 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 9: 31498 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 10: 31500 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 11: 31502 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 12: 31504 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 13: 31506 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 14: 31508 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 15: 31510 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 16: 31512 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 17: 31514 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 18: 31516 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 19: 31518 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 20: 31520 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 21: 31522 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 22: 31524 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 23: 31526 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 24: 31528 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 25: 31530 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 26: 31532 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 27: 31534 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 28: 31536 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 29: 31538 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 30: 31540 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 31: 31542 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 32: 31544 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 33: 31546 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 34: 31548 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 35: 31550 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 36: 31552 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 37: 31554 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 38: 31556 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 39: 31558 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 40: 31560 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 41: 31562 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 42: 31564 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 43: 31566 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 44: 31568 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 45: 31570 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 46: 31572 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 47: 31574 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 48: 31576 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 49: 31578 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 50: 31580 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 51: 31582 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 52: 31584 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 53: 31586 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 54: 31588 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 55: 31590 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 56: 31592 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 57: 31594 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 58: 31596 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 59: 31598 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 60: 31600 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 61: 31602 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 62: 31604 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 63: 31606 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 64: 31608 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 65: 31610 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 66: 31612 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 67: 31614 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 68: 31616 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 69: 31618 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 70: 31620 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 71: 31622 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 72: 31624 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 73: 31626 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 74: 31628 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 75: 31630 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 76: 31632 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 77: 31634 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 78: 31636 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 79: 31638 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 80: 31640 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 81: 31642 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 82: 31644 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 83: 31646 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 84: 31648 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 85: 31650 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 86: 31652 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 87: 31654 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 88: 31656 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 89: 31658 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 90: 31660 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 91: 31662 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 92: 31664 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 93: 31666 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 94: 31668 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 95: 31670 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 96: 31672 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 97: 31674 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 98: 31676 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 99: 31678 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 100: 31680 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/14.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-1-d-val.sh: line 101: 31682 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-b.pddl $1
