terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 1: 32302 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 2: 32304 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 3: 32306 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 4: 32308 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 5: 32310 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 6: 32312 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 7: 32314 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 8: 32316 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 9: 32318 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 10: 32320 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 11: 32322 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 12: 32324 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 13: 32326 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 14: 32328 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 15: 32330 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 16: 32332 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 17: 32338 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 18: 32340 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 19: 32342 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 20: 32344 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 21: 32346 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 22: 32360 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 23: 32362 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 24: 32364 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 25: 32366 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 26: 32368 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 27: 32370 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 28: 32372 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 29: 32376 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 30: 32378 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 31: 32380 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 32: 32382 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 33: 32384 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 34: 32386 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 35: 32388 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 36: 32390 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 37: 32392 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 38: 32394 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 39: 32396 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 40: 32398 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 41: 32400 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 42: 32402 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 43: 32404 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 44: 32406 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 45: 32408 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 46: 32410 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 47: 32412 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 48: 32414 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 49: 32416 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 50: 32418 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 51: 32420 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 52: 32422 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 53: 32424 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 54: 32426 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 55: 32428 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 56: 32430 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 57: 32432 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 58: 32434 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 59: 32436 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 60: 32438 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 61: 32440 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 62: 32442 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 63: 32444 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 64: 32446 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 65: 32448 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 66: 32450 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 67: 32452 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 68: 32454 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 69: 32456 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 70: 32458 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 71: 32460 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 72: 32462 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 73: 32464 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 74: 32466 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 75: 32468 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 76: 32470 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 77: 32472 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 78: 32474 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 79: 32476 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 80: 32478 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 81: 32480 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 82: 32482 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 83: 32484 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 84: 32486 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 85: 32488 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 86: 32490 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 87: 32492 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 88: 32494 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 89: 32496 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 90: 32498 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 91: 32500 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 92: 32502 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 93: 32504 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 94: 32506 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 95: 32508 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 96: 32510 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 97: 32512 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 98: 32514 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 99: 32516 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/19.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-1-4-a-val.sh: line 100: 32518 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-b.pddl $1
