terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 1:   358 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 2:   360 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 3:   362 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 4:   364 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 5:   366 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 6:   368 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 7:   370 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 8:   373 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 9:   375 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 10:   377 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 11:   379 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 12:   381 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 13:   383 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 14:   385 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 15:   387 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 16:   389 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 17:   391 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 18:   393 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 19:   395 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 20:   397 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 21:   399 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 22:   401 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 23:   403 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 24:   405 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 25:   407 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 26:   409 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 27:   411 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 28:   413 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 29:   415 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 30:   417 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 31:   419 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 32:   421 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 33:   423 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 34:   425 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 35:   427 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 36:   429 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 37:   431 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 38:   433 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 39:   435 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 40:   437 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 41:   439 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 42:   441 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 43:   443 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 44:   445 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 45:   447 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 46:   449 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 47:   451 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 48:   453 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 49:   455 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 50:   457 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 51:   459 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 52:   462 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 53:   464 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 54:   466 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 55:   468 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 56:   470 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 57:   472 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 58:   475 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 59:   478 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 60:   480 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 61:   482 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 62:   484 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 63:   486 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 64:   488 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 65:   490 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 66:   492 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 67:   494 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 68:   496 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 69:   498 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 70:   501 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 71:   503 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 72:   505 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 73:   508 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 74:   510 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 75:   512 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 76:   514 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 77:   516 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 78:   518 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 79:   520 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 80:   522 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 81:   524 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 82:   526 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 83:   528 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 84:   530 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 85:   532 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 86:   534 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 87:   536 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 88:   538 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 89:   540 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 90:   542 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 91:   544 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 92:   546 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 93:   548 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 94:   550 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 95:   552 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 96:   554 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 97:   556 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 98:   560 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 99:   562 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/22.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-3-2-d-val.sh: line 100:   564 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-a.pddl $1
