terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 1:  1653 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 2:  1655 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 3:  1657 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 4:  1659 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 5:  1661 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 6:  1663 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 7:  1665 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 8:  1667 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 9:  1669 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 10:  1671 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 11:  1673 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 12:  1675 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 13:  1677 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 14:  1679 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 15:  1681 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 16:  1683 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 17:  1685 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 18:  1687 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 19:  1689 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 20:  1691 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 21:  1693 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 22:  1695 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 23:  1697 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 24:  1699 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 25:  1701 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 26:  1703 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 27:  1705 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 28:  1707 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 29:  1709 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 30:  1734 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 31:  1737 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 32:  1740 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 33:  1742 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 34:  1744 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 35:  1746 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 36:  1748 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 37:  1750 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 38:  1752 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 39:  1754 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 40:  1758 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 41:  1760 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 42:  1762 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 43:  1764 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 44:  1766 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 45:  1768 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 46:  1770 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 47:  1772 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 48:  1774 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 49:  1776 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 50:  1778 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 51:  1780 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 52:  1782 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 53:  1784 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 54:  1786 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 55:  1788 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 56:  1792 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 57:  1794 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 58:  1800 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 59:  1802 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 60:  1804 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 61:  1806 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 62:  1808 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 63:  1810 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 64:  1812 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 65:  1814 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 66:  1816 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 67:  1818 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 68:  1820 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 69:  1822 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 70:  1824 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 71:  1826 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 72:  1828 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 73:  1830 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 74:  1832 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 75:  1834 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 76:  1836 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 77:  1838 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 78:  1840 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 79:  1842 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 80:  1844 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 81:  1846 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 82:  1848 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 83:  1850 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 84:  1852 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 85:  1854 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 86:  1856 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 87:  1858 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 88:  1860 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 89:  1862 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 90:  1864 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 91:  1866 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 92:  1868 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 93:  1870 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 94:  1872 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 95:  1874 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 96:  1878 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 97:  1880 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 98:  1882 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 99:  1884 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 100:  1886 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neglite.program'
./scripts/neg/ijcai19/list-val/list-NEGLITE-2-2-a-val.sh: line 101:  1889 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-b.pddl $1
