terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 1:  8444 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 2:  8446 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 3:  8448 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 4:  8450 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 5:  8452 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 6:  8454 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 7:  8456 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 8:  8458 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 9:  8460 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 10:  8462 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 11:  8464 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 12:  8466 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 13:  8468 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 14:  8470 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 15:  8472 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-10-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 16:  8474 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 17:  8476 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 18:  8478 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 19:  8480 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 20:  8482 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-11-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 21:  8484 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 22:  8486 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 23:  8488 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 24:  8490 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 25:  8492 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-12-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 26:  8494 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 27:  8496 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 28:  8498 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 29:  8500 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 30:  8502 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-13-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 31:  8504 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 32:  8506 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 33:  8508 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 34:  8510 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 35:  8512 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-14-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 36:  8514 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 37:  8516 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 38:  8518 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 39:  8520 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 40:  8522 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-15-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 41:  8524 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 42:  8526 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 43:  8528 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 44:  8530 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 45:  8532 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-16-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 46:  8534 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 47:  8536 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 48:  8538 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 49:  8540 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 50:  8542 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-17-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 51:  8544 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 52:  8546 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 53:  8548 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 54:  8550 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 55:  8552 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-18-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 56:  8554 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 57:  8556 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 58:  8558 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 59:  8560 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 60:  8562 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-19-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 61:  8564 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 62:  8566 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 63:  8568 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 64:  8570 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 65:  8572 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-20-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 66:  8576 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 67:  8578 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 68:  8580 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 69:  8582 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 70:  8584 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-21-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 71:  8586 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 72:  8588 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 73:  8590 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 74:  8592 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 75:  8594 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 76:  8596 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 77:  8598 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 78:  8600 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 79:  8602 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 80:  8604 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 81:  8606 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 82:  8608 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 83:  8610 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 84:  8612 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 85:  8614 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 86:  8616 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 87:  8618 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 88:  8620 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 89:  8622 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 90:  8624 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 91:  8626 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 92:  8628 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 93:  8630 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 94:  8632 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 95:  8634 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 96:  8636 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 97:  8638 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 98:  8640 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 99:  8642 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 100:  8644 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/list/29.neg.program'
./scripts/neg/ijcai19/list-val/list-NEG-2-2-a-val.sh: line 101:  8646 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/list/domain.pddl domains/neg/list/list-2-neg-a.pddl $1
