terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 1: 17236 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-9-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 2: 17238 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-9-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 3: 17240 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-9-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 4: 17242 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-9-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 5: 17244 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-9-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 6: 17246 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-10-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 7: 17248 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-10-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 8: 17250 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-10-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 9: 17252 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-10-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 10: 17254 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-10-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 11: 17256 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-11-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 12: 17258 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-11-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 13: 17260 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-11-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 14: 17262 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-11-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 15: 17264 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-11-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 16: 17266 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-12-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 17: 17268 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-12-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 18: 17270 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-12-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 19: 17272 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-12-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 20: 17274 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-12-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 21: 17276 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-13-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 22: 17278 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-13-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 23: 17280 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-13-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 24: 17282 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-13-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 25: 17284 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-13-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 26: 17286 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-14-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 27: 17288 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-14-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 28: 17290 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-14-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 29: 17292 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-14-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 30: 17294 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-14-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 31: 17296 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-15-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 32: 17298 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-15-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 33: 17300 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-15-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 34: 17302 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-15-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 35: 17304 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-15-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 36: 17306 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-16-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 37: 17308 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-16-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 38: 17310 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-16-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 39: 17312 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-16-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 40: 17314 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-16-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 41: 17316 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-17-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 42: 17318 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-17-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 43: 17320 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-17-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 44: 17322 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-17-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 45: 17324 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-17-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 46: 17326 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-18-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 47: 17328 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-18-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 48: 17330 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-18-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 49: 17332 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-18-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 50: 17334 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-18-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 51: 17336 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-19-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 52: 17338 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-19-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 53: 17340 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-19-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 54: 17342 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-19-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 55: 17344 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-19-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 56: 17346 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-20-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 57: 17348 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-20-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 58: 17350 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-20-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 59: 17352 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-20-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 60: 17354 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-20-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 61: 17356 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-21-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 62: 17358 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-21-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 63: 17360 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-21-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 64: 17362 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-21-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 65: 17364 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-21-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 66: 17366 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-3-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 67: 17368 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-7-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 68: 17370 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-8-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 69: 17372 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-1-pos-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 70: 17374 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-2-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 71: 17376 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-2-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 72: 17380 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-1-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 73: 17382 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-7-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 74: 17384 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-4-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 75: 17386 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-5-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 76: 17388 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-3-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 77: 17390 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-1-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 78: 17392 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-5-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 79: 17394 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-6-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 80: 17396 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-7-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 81: 17398 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-7-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 82: 17400 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-4-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 83: 17402 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-6-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 84: 17404 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-6-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 85: 17406 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-7-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 86: 17408 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-1-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 87: 17410 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-3-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 88: 17412 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-3-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 89: 17414 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-4-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 90: 17416 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-3-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 91: 17418 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-6-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 92: 17420 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-2-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 93: 17422 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-4-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 94: 17424 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-8-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 95: 17426 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-8-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 96: 17428 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-1-neg-b.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 97: 17430 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-2-neg-d.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 98: 17432 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-8-neg-a.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 99: 17434 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-5-neg-c.pddl $1
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/ijcai19/rp/38.neg.program'
./scripts/neg/ijcai19/rp-val/rp-NEG-4-1-d-val.sh: line 100: 17436 Aborted                 (core dumped) ./universal-planning-validator/validator/validate.bin -p domains/neg/rp/domain.pddl domains/neg/rp/rp-5-neg-d.pddl $1
